version: 0.0.1
report_title: LaTeX Template For an iDSI Technical Report
organizations:
  - National Center For Supercomputing Applications (NCSA)
  - Laboratory for Computation, Data, and Machine Learning
  - Univeristy of Illinois
authors:
  - Bhuvan Venkatesh:
      - 1
      - 2
  - Professor Brunner:
      - 2
      - 3
prereqs:
  - Another One